require 'no_equals/version'
require 'no_equals/use_cases/add'
require 'no_equals/use_cases/divide'
require 'no_equals/use_cases/get_result'
require 'no_equals/use_cases/multiply'
require 'no_equals/use_cases/push'
require 'no_equals/use_cases/subtract'
